### ISSUE TITLE
Bad Import/Missing Module

### ISSUE THREAD

**Issue by TheRealPhishyOne** [vijaysahuofficial/UserReCon#18]
pkg_resources module is missing and being requested
Termux installation

~/UserReCon $ python userrecon.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/UserReCon/userrecon.py", line 3, in <module>
    import pyfiglet
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/pyfiglet/__init__.py", line 11, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'

**Comment by TheRealPhishyOne** [comment]
pip install setuptools
fixed :-)
